services:
  postgres:
    image: postgres:18-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_management
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      retries: 5
      start_period: "10s"
      interval: "10s"
      timeout: "30s"
    volumes:
      - postgres-data:/var/lib/postgresql

  keycloak:
    build:
      context: ./keycloak
      dockerfile: Dockerfile
    command: ["start-dev", "--import-realm"]
    restart: always
    ports:
      - "9000:9000"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 9000

  jaeger:
    image: jaegertracing/all-in-one:1.72.0
    restart: always
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"

  backend:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - keycloak
    develop:
      watch:
        - action: rebuild
          path: ./backend/TaskManagement.Backend.csproj
        - action: sync+restart
          path: ./backend
          target: /app/
          ignore:
            - bin/
            - obj/

volumes:
  postgres-data:
